version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password

  backend_migrations:
    build:
      context: ../backend
    command: python3 manage.py migrate
    volumes:
      - ../backend/media:/app/media
      - ../backend/staticfiles:/app/static
    depends_on:
      - db
    environment:
      DB_ENABLE_PG: "true"
      DB_HOST: "db"
      DB_NAME: "foodgram"
      DB_USER: "foodgram_user"
      DB_PASSWORD: "foodgram_password"
      DB_PORT: 5432
    env_file:
      - ../backend/.env

  backend:
    build:
      context: ../backend
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ../backend/media:/app/media
      - ../backend/staticfiles:/app/static
    depends_on:
      - db
      - backend_migrations
    environment:
      DB_ENABLE_PG: "true"
      DB_HOST: "db"
      DB_NAME: "foodgram"
      DB_USER: "foodgram_user"
      DB_PASSWORD: "foodgram_password"
      DB_PORT: 5432
    env_file:
      - ../backend/.env


  frontend:
    build:
      context: ../frontend
    volumes:
      - frontend_static:/build_result

  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - frontend_static:/frontend
      - ../backend/media:/media
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pg_data:
  frontend_static:
