version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../backend/media:/app/media
      - ../backend/staticfiles:/app/static
    depends_on:
      - db
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ../frontend
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - ../backend/media:/media
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pg_data:
  static:
